/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: f0521a9f5c4cd3d959b77a9cd72b9b12)
interface __BaseEnv_CloudflareEnv {
  DB: D1Database;
  ASSETS: Fetcher;
  AUTH_URL: 'https://ielts-writing-app.tomo9634.workers.dev';
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./.open-next/worker');
  }
  interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, 'AUTH_URL'>
  > {}
}
